### PR TITLE
HF63: Images fixes #33

### LINKED ISSUE #33: Unhandled exception when uploading jpg file
image

### PR DESCRIPTION
**Pull request by tomejzen**
- image upload is optional
- directory is created if doesnt exist
- if no image uploaded default one is displayed

### CODE REVIEW

**Comment by krzysiekprzekwas** [comment]
Is this a fix for Unhandled exception when uploading jpg file #33 ?

File: Web/Controllers/AuctionsController.cs [hunk 1]
```diff
@@ -84,8 +84,12 @@ public async Task<IActionResult> Create(CreateAuctionViewModel model)
             var user = await _userManager.GetUserAsync(HttpContext.User);
             var auction = model.MapToAuction(user);
 
-            var imagePath = await _imageService.UploadImage(model.Image);
-            auction.ImagePath = imagePath;
+            if(model.Image != null)
```
Comment (krzysiekprzekwas) [inline Web/Controllers/AuctionsController.cs]: How about some default image when user does not provide one? It will create more consistent UI.
More bussines question than a review tho.
@SzymonPuszcz What do You think?

Comment (tomejzen) [reply Web/Controllers/AuctionsController.cs]: It's already implemented at Web/Extensions/MappingExtensions.cs line 123.
